<?php
/** @var Magento\Payment\Block\Form $block */

$code = $block->getMethodCode();
?>
<fieldset class="admin__fieldset payment-method"
          id="payment_form_<?= $block->escapeHtmlAttr($code) ?>"
          style="display:none;">
    <div class="admin__field _required">
        <label class="label admin__field-label">
            <span><?= $block->escapeHtml(__('CPF')) ?></span>
        </label>
        <div class="admin__field-control control">
            <div id="<?= $block->escapeHtmlAttr($code) ?>_national_identifier" class="admin__control-text hosted-control">
            </div>
            <div class="hosted-error">
                <?= $block->escapeHtml(__('Please, enter valid CPF')) ?>
            </div>
        </div>
    </div>
</fieldset>
